name: Chaching and Artifacts
on: [workflow_dispatch]
jobs:
    use-axios:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install Dependencies
              run: npm install
            - name: Use Axios
              uses: actions/github-script@v6
              with:
                script: | 
                    const axious = require ('axios');
                    const res = await axious ('https://icanhazdadjoke.com/', {headers: {Accept: 'text/plain'}})
                    console.log(res.data)
