name: Simple Action
on: [push]

jobs:
    checkout-action:
        runs-on: ubuntu-latest
        steps:
            - name: List Files Before
              run: ls -a
            - uses: actions/checkout@v3
            - name: List Files After
              run: ls -a
            
    Simple-action:
        runs-on: ubuntu-latest
        steps:
            - name: Simple JS Action
              id: greet
              uses: actions/hello-world-javascript-action@main
              with: 
                who-to-greet: Scott
            - name: Log greeting Time
              run: echo "${{steps.greet.outputs.time}}"