name: Calling Reusable Workflow
on:
    workflow_dispatch:
        inputs:
            name:
                description: 'Input description'
                type: string
                default: 'Scott'
                required: false

jobs:
    calling-a-reusable-workflow:
        uses: mck3nz1e/My-First-API/.github/workflows/reusable.yaml@master
        with: 
            name: '${{ inputs.name }}'
        secrets:
            access-token: ${{secrets.ACCESS_TOKEN}}


    calling-a-reusable-wf-in-same-repo:
        uses: ./.github/workflows/reusable-workflow.yaml
    
    using-reusable-wf-output:
        runs-on: ubuntu-latest
        needs: calling-a-reusable-wf-in-same-repo
        steps:
            - run: echo ${{ needs.calling-a-reusable-wf-in-same-repo.outputs.date }}