name: Variables And Secrets
on: [push]

jobs:
    log-vars:
        runs-on: ${{ vars.JOBS_RUNNER }}
        environment: "Production"
        env:
            BOOLEAN_SECRET: ${{ secrets.BOOLEAN_SECRET }}
            ENV-LEVEL-VAR: ${{ vars.ENV_LEVEL_VAR }}
            REPO-LEVEL-VAR: ${{ vars.REPO_LEVEL_VAR }}

        steps: 
            - name: Run only if BOOLEAN_SECRET is true
              if: env.BOOLEAN_SECRET == 'true'
              run: echo "i ran"

            - name: Log Vars
              run: |
                echo '${{ vars.JOBS_RUNNER}}'
                echo "REPO_LEVELVAR: $REPO_LEVEL_VAR"
                echo "ENV_LEVEL_VAR: $ENV_LEVEL_VAR"