name: Variables And Secrets
on: [push]

jobs:

    decrypt-file:
      runs-on: ${{ vars.JOBS_RUNNER }}
      steps:
        - uses: actions/checkout@v3
        - name: Decrypt File
          env: 
            PASSPHRASE: ${{ secrets.PASSPHRASE}}
          run: |
            mkdir $HOME/secrets
            gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" --output $HOME/secrets/secret.json secret.json.gpg

        - name: View Encypted File Contents (NEVER DO THIS! JUST FOR TEST)
          run: cat $HOME/secrets/secret.json

    log-vars:
        runs-on: ${{ vars.JOBS_RUNNER }}
        environment: "Staging"
        env:
            BOOLEAN_SECRET: ${{ secrets.BOOLEAN_SECRET }}
            ENV_LEVEL_VAR: ${{ vars.ENV_LEVEL_VAR }}
            REPO_LEVEL_VAR: ${{ vars.REPO_LEVEL_VAR }}

        steps: 
            - name: Run only if BOOLEAN_SECRET is true
              if: env.BOOLEAN_SECRET == 'true'
              run: echo "i ran"

            - name: Log Vars
              run: |
                echo '${{ vars.JOBS_RUNNER}}'
                echo "REPO_LEVEL_VAR: $REPO_LEVEL_VAR"
                echo "ENV_LEVEL_VAR: $ENV_LEVEL_VAR"